#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=8gb,walltime=0:15:00
#PBS -N extractTCKfromWMC

mkdir -p output/tcks

echo "extracting tracts"
singularity exec -e docker://brainlife/mcr:r2019a ./compiled/main




